### ISSUE TITLE
Data from ws.recv sometimes is partial

### ISSUE THREAD

**Issue by sliterok** [Vovaman/micropython_async_websocket_client#3]
I was trying to make RGB strip work with this, but if I send ~10 packets/second it starts to receive partial data. I'm not sure if it's desired behavior because my code expects data with fixed length and anything less than that will throw error. I've tried to rewrite that to use Queue I still get the same trouble...
![image](https://user-images.githubusercontent.com/12751644/170548491-db233e97-1ce2-40cf-900b-3fdb3369ee8b.png)

**Comment by Vovaman** [comment]
It is preferable to view complete example. May be you've got phisycal limitations of your controller. Ten packets per second - it is approximately 100 ms per packet. When I've tested this client, time parameters modifications strongly affect behaviour.

**Comment by sliterok** [comment]
Yeah, I've also tried mqtt and it wasn't able to handle this kind of throughput, though it was a little better. In the end I've settled on raw UDPing it. Works almost flawless :)

**Comment by Vovaman** [comment]
Yes. This client is not suitable for such throughput, at least on ESP32S.
