### ISSUE TITLE
Add wss support

### ISSUE THREAD

**Issue by Vovaman** [Vovaman/micropython_async_websocket_client#4]
Client has to support wss protocol.
Extend https://github.com/Vovaman/example_async_websocket when finish this issue.

**Comment by Vovaman** [comment]
Set to pause. I monitor SSLContext realization in micropython project.

**Comment by f321x** [comment]
@Vovaman As the non async version now has wss support, would it be possible to port this or is there still something missing?

**Comment by Vovaman** [comment]
I want to realize full wss functionality, including certificate verification. There is trouble while decode certificate. Waiting for SSLContext realization. Will check it again this week.
